spring:
  application:
    name: tasklist
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password: password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: dHl3ZXJ0ZXd2eXR3ZXZydHl3ZXZydHlld3ZyeXRld3I=
    access: 3600000
    refresh: 2592000000


